services:
  db:
    image: postgres:14
    container_name: postgres-db-prod
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-prod
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: flask-backend-prod
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: react-frontend-prod
    ports:
      - "3000:80" # React prod server runs on 80
    env_file:
      - ./frontend/.env.production
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app

volumes:
  pgdata_prod:
