FROM python:3.13-slim

# Set workdir
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Command to run the app
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app.src:app"]